name: plotlylab-environment
channels:
  - main
  - plotly
  - r
  - conda-forge
dependencies:
  - python>3.6
  - numpy
  - pandas
  - notebook>5.2
  - matplotlib
  - ipywidgets=7
  - plotly
  - pip
  - appmode
  - pip:
    - plotly==4.1.0
    - plyfile
